format = """
[](#2e3440)\
$username\
$hostname\
[](fg:#2e3440 bg:#3b4252)\
$directory\
[](fg:#3b4252 bg:#495469)\
$git_branch\
$git_status\
[](fg:#495469 bg:#566176)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#566176 bg:#5e81ac)\
$docker_context\
[](fg:#5e81ac bg:#3a7f92)\
$cmd_duration\
[ ](fg:#3a7f92)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#2e3440 fg:bold yellow"
style_root = "bg:#2e3440 fg:bold cyan"
format = '[$user]($style)'

[hostname]
disabled = false
ssh_only = false
# trim_at = '.companyname.com'
style = "bg:#2e3440 fg:bold green"
format = '[@$hostname$ssh_symbol ]($style)'

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#495469"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#495469"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#566176"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[cmd_duration]
style = "fg:bold yellow bg:#3a7f92"
format = '[$duration]($style)'